name: Maps
on:
  push:
    branches:
    - main
    - sauce
    - south
  pull_request:
    branches:
    - main
    

jobs:
   compile_all_maps:
    name: Compile All Maps
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Cache
        uses: actions/cache@v3
        with:
          path: $HOME/BYOND
          key: ${{ runner.os }}-byond
      - name: Compile All Maps
        run: |
          chmod +x tools/ci/install_byond.sh
          tools/ci/install_byond.sh
          source $HOME/BYOND/byond/bin/byondsetup
          chmod +x tools/ci/generate_maplist.sh
          tools/ci/generate_maplist.sh
          chmod +x tools/ci/dm.sh
          tools/ci/dm.sh -Mci_map_testing paradise.dme
